# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import connection_pb2 as connection__pb2


class ParsingStub(object):
    """/ Сервис для парсинга задач
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseUri = channel.unary_unary(
                '/myconnect.Parsing/ParseUri',
                request_serializer=connection__pb2.Request.SerializeToString,
                response_deserializer=connection__pb2.Response.FromString,
                )


class ParsingServicer(object):
    """/ Сервис для парсинга задач
    """

    def ParseUri(self, request, context):
        """/ Парсит URI и возвращает информацию о задаче
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParsingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseUri': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseUri,
                    request_deserializer=connection__pb2.Request.FromString,
                    response_serializer=connection__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myconnect.Parsing', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Parsing(object):
    """/ Сервис для парсинга задач
    """

    @staticmethod
    def ParseUri(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myconnect.Parsing/ParseUri',
            connection__pb2.Request.SerializeToString,
            connection__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
